using System;
using System.Windows.Controls;

namespace FocusScoringGUI
{
    public class DataGridClickable : DataGrid
    {
        protected override void OnAutoGeneratedColumns(EventArgs e)
        {
            base.OnAutoGeneratedColumns(e);
        }
    }
}